---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Namespace
metadata:
  name: bot-buffet
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bot-buffet-wordpress
  namespace: bot-buffet
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "22.4.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: "gurghet"
    wordpressEmail: "gurghet@proton.me"
    wordpressBlogName: "Bot Buffet"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: "traefik"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot-buffet-wordpress-ingress
  namespace: bot-buffet
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bot-buffet-wordpress
            port:
              name: http
